### ISSUE TITLE
error compiling with gcc 4.5

### ISSUE THREAD

**Issue by mckaygerhard** [Aleph-One-Marathon/alephone#8]
when i try to compiling with gcc 4.5 stable got that error:

```
InfoTree.h:123: error: ISO C++ forbids declaration of ‘any_range’ with no type
```

how could i fix this problem with that gcc version please?

**Comment by darealshinji** [comment]
I can build it with gcc 4.4. Maybe your Boost version is too old?

**Comment by mckaygerhard** [comment]
hello i now revised and seems its too older, i fusioned the commit that improves the treeinfo and now compiles with and if-else macro that peform boots version detection, but now i have that error: `WadImageCache.cpp:126: error: ‘to_string’ is not a member of ‘boost::uuids’` 

due i'm a nebie in boots and the treeinfo are very new i cannot revert the commit that integrate the savestte and separate image cache.. so what can be do?

**Comment by mckaygerhard** [comment]
sorry the version of boost was 1.40 now tested with 1.42 i need to build with 1.42 maximun due performance issues and cheap space in device...

there's some way to solve the  error: `WadImageCache.cpp:126: error: ‘to_string’ is not a member of ‘boost::uuids’` to able to compile a bit the exelent engine in my setup device? its an pc device for childrens so resource3s are very limited.. that's why i want to backport this game to that kiss see benefitcs from free soft and games are also available.. so please help me

**Comment by darealshinji** [comment]
You could try to build alephone on a newer system and link most dependencies statically. The resulting binary should work on most Linux systems.

Here's a script for Ubuntu 14.04 to build a portable binary (still requires OpenGL and SDL1.2 runtime):
``` sh
#!/bin/sh
set -e
set -v

git clone --depth 1 https://github.com/Aleph-One-Marathon/alephone.git
cd alephone
git clone --depth 1 --branch release/2.8 https://github.com/FFmpeg/FFmpeg.git ffmpeg
#git clone --depth 1 git://source.ffmpeg.org/ffmpeg.git ffmpeg
curdir="$PWD"

cd ffmpeg
./configure --prefix="$curdir/libs" --enable-small --disable-runtime-cpudetect \
  --disable-debug --disable-asm --disable-programs --disable-doc --disable-hwaccels \
  --disable-bzlib --disable-lzma --disable-sdl --disable-xlib --disable-zlib
make -j4
make install
cd ..

sudo apt-get install libsdl1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev libboost-all-dev libpng12-dev

autoreconf -if
export PKG_CONFIG_PATH=libs/lib/pkgconfig
export CFLAGS="-O3 -Wall -Wno-sign-compare -Wno-maybe-uninitialized -fstack-protector -fno-strict-aliasing -ffunction-sections -fdata-sections -D_FORTIFY_SOURCE=2"
export CXXFLAGS="$CFLAGS -Wno-reorder -Wno-narrowing"
export LDFLAGS="-s -Wl,-z,relro -Wl,-z,defs -Wl,--gc-sections"
./configure --without-mad --without-sndfile --without-vorbis --without-smpeg \
  --without-speex --without-alsa --without-curl --without-zzip
make -j4

cd Source_Files
g++ $LDFLAGS -o alephone shell.o shell_misc.o \
CSeries/libcseries.a Files/libfiles.a FFmpeg/libffmpeg.a GameWorld/libgameworld.a Input/libinput.a Lua/liba1lua.a \
Misc/libmisc.a ModelView/libmodelview.a Network/libnetwork.a Network/Metaserver/libmetaserver.a \
RenderMain/librendermain.a RenderOther/librenderother.a Sound/libsound.a XML/libxml.a CSeries/libcseries.a \
Files/libfiles.a FFmpeg/libffmpeg.a GameWorld/libgameworld.a Input/libinput.a Lua/liba1lua.a Misc/libmisc.a \
ModelView/libmodelview.a Network/libnetwork.a Network/Metaserver/libmetaserver.a RenderMain/librendermain.a \
RenderOther/librenderother.a Sound/libsound.a TCPMess/libtcpmess.a XML/libxml.a LibNAT/libnat.a \
-Wl,-Bstatic -lexpat -lpng12 -lz -Wl,-Bdynamic \
-L"$curdir/libs/lib" -lavformat -lavcodec -lswresample -lswscale -lavutil -lm \
-Wl,-Bstatic -lboost_filesystem -lboost_system -Wl,-Bdynamic \
-lSDL -lSDL_net -lSDL_ttf -lGL -lGLU -pthread -lpthread -static-libstdc++ -static-libgcc
```

**Comment by mckaygerhard** [comment]
build on a newer system raises always on glibc differences and sdtlib problems due optimization levels and changes between newer versions of both gcc and glibc, when i running the result binary get a error loading the libc6 library..

**i'll translate this issue to the #7 due the problem are not gcc are boost compatibility.. **

**i solved most problem but now i have a missing funtionality hex conversion** due commit f938a954a000bab82873768a1ee906c144db1a63, please see in the #7 and help me
