### ISSUE TITLE
Issue building on Alpine 3.21

### ISSUE THREAD

**Issue by adamthiede** [Aleph-One-Marathon/alephone#530]
I've been able to build Alephone on previous versions of Alpine with no issues for a few years now, but have not been able to build it yet on 3.21; I receive this error:

```
In file included from game_wad.cpp:93:
../../Source_Files/GameWorld/effects.h:156:17: error: expected ',' or '...' before '(' token
  156 | #define effects (EffectList.data())
      |                 ^
../../Source_Files/GameWorld/effects.h:156:17: error: expected ',' or '...' before '(' token
  156 | #define effects (EffectList.data())
      |                 ^
```

Alpine is musl-based so that may be part of the issue. I'm fine carrying a patch in my personal builds, I'd just like to know how to work around this, if I can.

Thank you!

**Comment by treellama** [comment]
I'm afraid I don't understand why this would be an error. What compiler are you using?

**Comment by adamthiede** [comment]
Using gcc, pretty recent versions of everything. Here's the output of ./configure.

[configure-output.txt](https://github.com/user-attachments/files/18347548/configure-output.txt)

**Comment by adamthiede** [comment]
I get the same error on Arch Linux, which also has GCC14.

```
In file included from game_wad.cpp:93:
../../Source_Files/GameWorld/effects.h:156:17: error: expected ‘,’ or ‘...’ before ‘(’ token
  156 | #define effects (EffectList.data())
      |                 ^
../../Source_Files/GameWorld/effects.h:156:17: error: expected ‘,’ or ‘...’ before ‘(’ token
  156 | #define effects (EffectList.data())
      |                 ^
```

**Comment by djvs** [comment]
Same problem.  Diff attached that removes the `effects` macro.  Build still failing on Arch-likes for other reasons.

[effects.diff.txt](https://github.com/user-attachments/files/18389908/effects.diff.txt)

**Comment by treellama** [comment]
Can you post the actual gcc version? I just built with 14.2.0 in ubuntu with no issues. That effects macro is valid syntax, I hesitate to remove it just because of one buggy compiler version.

**Comment by djvs** [comment]
g++ (GCC) 14.2.1 20240910

**Comment by treellama** [comment]
Where are you getting 14.2.1 from? The latest tarball on GNU's ftp is 14.2.0 https://ftp.gnu.org/gnu/gcc/gcc-14.2.0/

**Comment by djvs** [comment]
https://archlinux.org/packages/core/x86_64/gcc/ gcc 14.2.1+r134+gab884fffe3fc-2

**Comment by treellama** [comment]
compiles fine with gcc (GCC) 14.2.1 20240912 as well (with --disable-ffmpeg)...

I wonder if there are some extra patches or something else at play. I'll try to allocate time to figure out how to install Arch in a VM

**Comment by djvs** [comment]
I was doing a local build with Artix (Arch-based) updated a few days ago.

**Comment by adamthiede** [comment]
> I wonder if there are some extra patches or something else at play. I'll try to allocate time to figure out how to install Arch in a VM

If you don't mind using docker/podman, distrobox would be a quick way to test it.

**Comment by brad0** [comment]
I was going to file an issue, but happened to click on this one and noticed the mentioned error seems to be the same as what we noticed on OpenBSD after updating OpenAL to 1.24.x. We use Clang as a compiler.

```
c++ -DHAVE_CONFIG_H -I. -I../..  -I../../Source_Files/CSeries -I../../Source_Files/GameWorld -I../../Source_Files/Input -I../../Source_Files/Misc -I../../Source_Files/ModelView -I../../Source_Files/Network -I../../Source_Files/Network/Metaserver -I../../Source_Files/TCPMess -I../../Source_Files/RenderMain -I../../Source_Files/RenderOther -I../../Source_Files/Sound -I../../Source_Files/XML -I../../Source_Files -I/usr/local/include/libpng16 -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include/SDL2 -I/usr/local/include -DHWY_SHARED_DEFINE -DAVIF_DLL -I/usr/local/include/webp -I/usr/X11R6/include -D_REENTRANT -I/usr/local/include -I/usr/local/include/AL -I/usr/local/include -I/usr/local/include/opus  -I/usr/local/include/SDL2 -I/usr/X11R6/include -D_REENTRANT -I/usr/local/include/SDL2 -I/usr/X11R6/include -D_REENTRANT -I/usr/local/include -I/usr/local/include/SDL2 -I/usr/X11R6/include -D_REENTRANT -DSDL  -O2 -pipe -MT game_wad.o -MD -MP -MF $depbase.Tpo -c -o game_wad.o game_wad.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from game_wad.cpp:102:
In file included from ../../Source_Files/Misc/preferences.h:59:
In file included from ../../Source_Files/Sound/SoundManager.h:29:
In file included from ../../Source_Files/Sound/SoundPlayer.h:4:
In file included from ../../Source_Files/Sound/AudioPlayer.h:5:
/usr/local/include/AL/alext.h:821:90: error: expected ')'
typedef void (AL_APIENTRY *LPALGENEFFECTSDIRECT)(ALCcontext *context, ALsizei n, ALuint *effects) AL_API_NOEXCEPT17;
                                                                                         ^
../../Source_Files/GameWorld/effects.h:156:28: note: expanded from macro 'effects'
#define effects (EffectList.data())
                           ^
/usr/local/include/AL/alext.h:821:90: note: to match this '('
../../Source_Files/GameWorld/effects.h:156:17: note: expanded from macro 'effects'
#define effects (EffectList.data())
                ^
In file included from game_wad.cpp:102:
In file included from ../../Source_Files/Misc/preferences.h:59:
In file included from ../../Source_Files/Sound/SoundManager.h:29:
In file included from ../../Source_Files/Sound/SoundPlayer.h:4:
In file included from ../../Source_Files/Sound/AudioPlayer.h:5:
/usr/local/include/AL/alext.h:822:99: error: expected ')'
typedef void (AL_APIENTRY *LPALDELETEEFFECTSDIRECT)(ALCcontext *context, ALsizei n, const ALuint *effects) AL_API_NOEXCEPT17;
                                                                                                  ^
../../Source_Files/GameWorld/effects.h:156:28: note: expanded from macro 'effects'
#define effects (EffectList.data())
                           ^
/usr/local/include/AL/alext.h:822:99: note: to match this '('
../../Source_Files/GameWorld/effects.h:156:17: note: expanded from macro 'effects'
#define effects (EffectList.data())
                ^
2 errors generated.
```

**Comment by treellama** [comment]
That's a different error (your clang correctly handled the macro), but it's still valid.

**Comment by brad0** [comment]
> That's a different error (your clang correctly handled the macro), but it's still valid.

Oh, Ok. I will open another issue. Thanks.
