### ISSUE TITLE
Compile Errors After Ubuntu 22.10 Upgrade

### ISSUE THREAD

**Issue by dslipp** [Aleph-One-Marathon/alephone#393]
I'm really not very good at this, but here's what I'm getting.

---

SDL_ffmpeg.c: In function ‘SDL_ffmpegFree’:
SDL_ffmpeg.c:260:25: warning: implicit declaration of function ‘avcodec_free_context’; did you mean ‘avformat_free_context’? [-Wimplicit-function-declaration]
  260 |         if ( old->_ctx) avcodec_free_context( &old->_ctx );
      |                         ^~~~~~~~~~~~~~~~~~~~
      |                         avformat_free_context
SDL_ffmpeg.c: In function ‘SDL_ffmpegOpen’:
SDL_ffmpeg.c:408:34: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  408 |                 AVCodec *codec = avcodec_find_decoder( stream->_ffmpeg->codecpar->codec_id );
      |                                  ^~~~~~~~~~~~~~~~~~~~
SDL_ffmpeg.c:416:32: warning: implicit declaration of function ‘avcodec_alloc_context3’; did you mean ‘avio_alloc_context’? [-Wimplicit-function-declaration]
  416 |                 stream->_ctx = avcodec_alloc_context3(codec);
      |                                ^~~~~~~~~~~~~~~~~~~~~~
      |                                avio_alloc_context
SDL_ffmpeg.c:416:30: warning: assignment to ‘struct AVCodecContext *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  416 |                 stream->_ctx = avcodec_alloc_context3(codec);
      |                              ^
SDL_ffmpeg.c:417:38: warning: implicit declaration of function ‘avcodec_parameters_to_context’; did you mean ‘avcodec_parameters_copy’? [-Wimplicit-function-declaration]
  417 |                 if (!stream->_ctx || avcodec_parameters_to_context(stream->_ctx, stream->_ffmpeg->codecpar) < 0
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      avcodec_parameters_copy
SDL_ffmpeg.c:418:24: warning: implicit declaration of function ‘avcodec_open2’; did you mean ‘avio_open2’? [-Wimplicit-function-declaration]
  418 |                     || avcodec_open2(stream->_ctx, NULL, NULL ) < 0 || avcodec_parameters_from_context(stream->_ffmpeg->codecpar, stream->_ctx) < 0)
      |                        ^~~~~~~~~~~~~
      |                        avio_open2
SDL_ffmpeg.c:418:72: warning: implicit declaration of function ‘avcodec_parameters_from_context’; did you mean ‘avcodec_parameters_free’? [-Wimplicit-function-declaration]
  418 |                     || avcodec_open2(stream->_ctx, NULL, NULL ) < 0 || avcodec_parameters_from_context(stream->_ffmpeg->codecpar, stream->_ctx) < 0)
      |                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                        avcodec_parameters_free
SDL_ffmpeg.c:428:43: warning: implicit declaration of function ‘avcodec_alloc_frame’; did you mean ‘avcodec_get_name’? [-Wimplicit-function-declaration]
  428 |                     stream->decodeFrame = avcodec_alloc_frame();
      |                                           ^~~~~~~~~~~~~~~~~~~
      |                                           avcodec_get_name
SDL_ffmpeg.c:428:41: warning: assignment to ‘struct AVFrame *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  428 |                     stream->decodeFrame = avcodec_alloc_frame();
      |                                         ^
SDL_ffmpeg.c:462:34: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  462 |                 AVCodec *codec = avcodec_find_decoder( file->_ffmpeg->streams[i]->codecpar->codec_id );
      |                                  ^~~~~~~~~~~~~~~~~~~~
SDL_ffmpeg.c:470:30: warning: assignment to ‘struct AVCodecContext *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  470 |                 stream->_ctx = avcodec_alloc_context3(codec);
      |                              ^
SDL_ffmpeg.c:479:21: warning: ‘channel_layout’ is deprecated [-Wdeprecated-declarations]
  479 |                     int channel_layout = stream->_ffmpeg->codecpar->channel_layout ? stream->_ffmpeg->codecpar->channel_layout :
      |                     ^~~
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:314,
                 from SDL_ffmpeg.c:44:
/usr/include/x86_64-linux-gnu/libavcodec/codec_par.h:166:14: note: declared here
  166 |     uint64_t channel_layout;
      |              ^~~~~~~~~~~~~~
SDL_ffmpeg.c:479:21: warning: ‘channel_layout’ is deprecated [-Wdeprecated-declarations]
  479 |                     int channel_layout = stream->_ffmpeg->codecpar->channel_layout ? stream->_ffmpeg->codecpar->channel_layout :
      |                     ^~~
/usr/include/x86_64-linux-gnu/libavcodec/codec_par.h:166:14: note: declared here
  166 |     uint64_t channel_layout;
      |              ^~~~~~~~~~~~~~
SDL_ffmpeg.c:480:25: warning: ‘channels’ is deprecated [-Wdeprecated-declarations]
  480 |                         (stream->_ffmpeg->codecpar->channels == 2 ? AV_CH_LAYOUT_STEREO : AV_CH_LAYOUT_MONO);
      |                         ^
/usr/include/x86_64-linux-gnu/libavcodec/codec_par.h:172:14: note: declared here
  172 |     int      channels;
      |              ^~~~~~~~
SDL_ffmpeg.c:482:21: warning: ‘swr_alloc_set_opts’ is deprecated [-Wdeprecated-declarations]
  482 |                     stream->swr_context = swr_alloc_set_opts(stream->swr_context, channel_layout, AV_SAMPLE_FMT_S16,
      |                     ^~~~~~
In file included from SDL_ffmpeg.c:47:
/usr/include/x86_64-linux-gnu/libswresample/swresample.h:260:20: note: declared here
  260 | struct SwrContext *swr_alloc_set_opts(struct SwrContext *s,
      |                    ^~~~~~~~~~~~~~~~~~
SDL_ffmpeg.c: In function ‘SDL_ffmpegCreateAudioFrame’:
SDL_ffmpeg.c:763:86: error: invalid use of undefined type ‘struct AVCodecContext’
  763 |         bytes = file->audioStream->encodeAudioInputSize * 2 * file->audioStream->_ctx->channels;
      |                                                                                      ^~
SDL_ffmpeg.c: In function ‘SDL_ffmpegFlush’:
SDL_ffmpeg.c:1124:13: warning: implicit declaration of function ‘avcodec_flush_buffers’ [-Wimplicit-function-declaration]
 1124 |             avcodec_flush_buffers( file->audioStream->_ctx );
      |             ^~~~~~~~~~~~~~~~~~~~~
SDL_ffmpeg.c: In function ‘SDL_ffmpegGetAudioSpec’:
SDL_ffmpeg.c:1356:44: error: invalid use of undefined type ‘struct AVCodecContext’
 1356 |         spec.freq = file->audioStream->_ctx->sample_rate;
      |                                            ^~
SDL_ffmpeg.c:1357:59: error: invalid use of undefined type ‘struct AVCodecContext’
 1357 |         spec.channels = ( uint8_t )file->audioStream->_ctx->channels;
      |                                                           ^~
SDL_ffmpeg.c: In function ‘SDL_ffmpegAudioDuration’:
SDL_ffmpeg.c:1424:123: error: invalid use of undefined type ‘struct AVCodecContext’
 1424 |  file->audioStream->frameCount * file->audioStream->encodeAudioInputSize / ( file->audioStream->_ctx->sample_rate / 1000 );
      |                                                                                                     ^~

SDL_ffmpeg.c: In function ‘SDL_ffmpegVideoDuration’:
SDL_ffmpeg.c:1461:97: error: invalid use of undefined type ‘struct AVCodecContext’
 1461 |             duration = av_rescale( 1000 * file->videoStream->frameCount, file->videoStream->_ctx->time_base.num, file->videoStream->_ctx->time_base.den );
      |                                                                                                 ^~
SDL_ffmpeg.c:1461:137: error: invalid use of undefined type ‘struct AVCodecContext’
 1461 | 000 * file->videoStream->frameCount, file->videoStream->_ctx->time_base.num, file->videoStream->_ctx->time_base.den );
      |                                                                                                     ^~

SDL_ffmpeg.c: In function ‘SDL_ffmpegGetVideoSize’:
SDL_ffmpeg.c:1498:37: error: invalid use of undefined type ‘struct AVCodecContext’
 1498 |         *w = file->videoStream->_ctx->width;
      |                                     ^~
SDL_ffmpeg.c:1499:37: error: invalid use of undefined type ‘struct AVCodecContext’
 1499 |         *h = file->videoStream->_ctx->height;
      |                                     ^~
SDL_ffmpeg.c: In function ‘SDL_ffmpegDecodeAudioFrame’:
SDL_ffmpeg.c:1959:43: error: invalid use of undefined type ‘struct AVCodecContext’
 1959 |     int channels = file->audioStream->_ctx->channels;
      |                                           ^~
SDL_ffmpeg.c:2019:5: error: unknown type name ‘AVCodecContext’; use ‘struct’ keyword to refer to the type
 2019 |     AVCodecContext *avctx = file->audioStream->_ctx;
      |     ^~~~~~~~~~~~~~
      |     struct 
SDL_ffmpeg.c:2019:29: warning: initialization of ‘int *’ from incompatible pointer type ‘struct AVCodecContext *’ [-Wincompatible-pointer-types]
 2019 |     AVCodecContext *avctx = file->audioStream->_ctx;
      |                             ^~~~
SDL_ffmpeg.c:2021:27: warning: initialization of ‘AVFrame *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2021 |         AVFrame *dframe = avcodec_alloc_frame();
      |                           ^~~~~~~~~~~~~~~~~~~
SDL_ffmpeg.c:2022:5: warning: implicit declaration of function ‘avcodec_get_frame_defaults’ [-Wimplicit-function-declaration]
 2022 |     avcodec_get_frame_defaults(dframe);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
SDL_ffmpeg.c:2026:15: warning: implicit declaration of function ‘avcodec_send_packet’; did you mean ‘av_append_packet’? [-Wimplicit-function-declaration]
 2026 |     int len = avcodec_send_packet( avctx, pack );
      |               ^~~~~~~~~~~~~~~~~~~
      |               av_append_packet
SDL_ffmpeg.c:2036:12: warning: implicit declaration of function ‘avcodec_receive_frame’; did you mean ‘avcodec_profile_name’? [-Wimplicit-function-declaration]
 2036 |     while (avcodec_receive_frame(avctx, dframe) == 0) {
      |            ^~~~~~~~~~~~~~~~~~~~~
      |            avcodec_profile_name
SDL_ffmpeg.c:2039:9: warning: ‘channel_layout’ is deprecated [-Wdeprecated-declarations]
 2039 |         convertedFrame->channel_layout = dframe->channel_layout;
      |         ^~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/libavutil/hwcontext.h:23,
                 from /usr/include/x86_64-linux-gnu/libavcodec/codec.h:27,
                 from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:313:
/usr/include/x86_64-linux-gnu/libavutil/frame.h:510:14: note: declared here
  510 |     uint64_t channel_layout;
      |              ^~~~~~~~~~~~~~
SDL_ffmpeg.c:2039:9: warning: ‘channel_layout’ is deprecated [-Wdeprecated-declarations]
 2039 |         convertedFrame->channel_layout = dframe->channel_layout;
      |         ^~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/libavutil/frame.h:510:14: note: declared here
  510 |     uint64_t channel_layout;
      |              ^~~~~~~~~~~~~~
SDL_ffmpeg.c:2052:9: warning: ‘channels’ is deprecated [-Wdeprecated-declarations]
 2052 |         int data_size = av_samples_get_buffer_size(&plane_size, convertedFrame->channels, convertedFrame->nb_samples, convertedFrame->format, 1);
      |         ^~~
/usr/include/x86_64-linux-gnu/libavutil/frame.h:643:9: note: declared here
  643 |     int channels;
      |         ^~~~~~~~
SDL_ffmpeg.c:2061:9: warning: ‘channels’ is deprecated [-Wdeprecated-declarations]
 2061 |         if (planar && convertedFrame->channels > 1)
      |         ^~
/usr/include/x86_64-linux-gnu/libavutil/frame.h:643:9: note: declared here
  643 |     int channels;
      |         ^~~~~~~~
SDL_ffmpeg.c:2065:13: warning: ‘channels’ is deprecated [-Wdeprecated-declarations]
 2065 |             for (ch = 1; ch < convertedFrame->channels; ch++)
      |             ^~~
/usr/include/x86_64-linux-gnu/libavutil/frame.h:643:9: note: declared here
  643 |     int channels;
      |         ^~~~~~~~
SDL_ffmpeg.c: In function ‘SDL_ffmpegDecodeVideoFrame’:
SDL_ffmpeg.c:2218:67: error: invalid use of undefined type ‘struct AVCodecContext’
 2218 |                                            file->videoStream->_ctx->width,
      |                                                                   ^~
SDL_ffmpeg.c:2219:67: error: invalid use of undefined type ‘struct AVCodecContext’
 2219 |                                            file->videoStream->_ctx->height,
      |                                                                   ^~
SDL_ffmpeg.c:2220:67: error: invalid use of undefined type ‘struct AVCodecContext’
 2220 |                                            file->videoStream->_ctx->pix_fmt,
      |                                                                   ^~
SDL_ffmpeg.c:2226:55: error: invalid use of undefined type ‘struct AVCodecContext’
 2226 |                                file->videoStream->_ctx->height,
      |                                                       ^~
SDL_ffmpeg.c:2232:67: error: invalid use of undefined type ‘struct AVCodecContext’
 2232 |                                            file->videoStream->_ctx->width,
      |                                                                   ^~
SDL_ffmpeg.c:2233:67: error: invalid use of undefined type ‘struct AVCodecContext’
 2233 |                                            file->videoStream->_ctx->height,
      |                                                                   ^~
SDL_ffmpeg.c:2234:67: error: invalid use of undefined type ‘struct AVCodecContext’
 2234 |                                            file->videoStream->_ctx->pix_fmt,
      |                                                                   ^~
SDL_ffmpeg.c:2240:55: error: invalid use of undefined type ‘struct AVCodecC

**Comment by Kolfering** [comment]
Master should indeed compile with ffmpeg 4 to 5.0 but Ubuntu 22.10 is getting ffmpeg 5.1 package which is not tested/supported yet. If you don't care about recording playbacks you can just `./configure --without-ffmpeg ` or else you will have to downgrade your ffmpeg package.

**Comment by dslipp** [comment]
Thanks for both responses! I'm going to try the second, as it's simpler.

**Comment by dslipp** [comment]
The latest update fixes the errors. It compiles, and it runs!
