### ISSUE TITLE
AlephOne 1.9 cannot be build with gcc 14.1. It breaks in PortForward.cpp:27:42

### ISSUE THREAD

**Issue by FredBezies** [Aleph-One-Marathon/alephone#504]
Hello.

I tried to build Alephone with gcc 14.1 but it breaks with this error message:

```
PortForward.cpp:27:42: error: too few arguments to function 'int UPNP_GetValidIGD(UPNPDev*, UPNPUrls*, IGDdatas*, char*, int, char*, int)'
   27 |         auto igd_found = UPNP_GetValidIGD(devlist.get(), &urls_, &data_, lanaddr, sizeof(lanaddr));
      |                          ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from PortForward.h:31,
                 from PortForward.cpp:1:
/usr/include/miniupnpc/miniupnpc.h:122:1: note: declared here
  122 | UPNP_GetValidIGD(struct UPNPDev * devlist,
      | ^~~~~~~~~~~~~~~~
make[4]: *** [Makefile:492: PortForward.o] Error 1
```

**Comment by Kolfering** [comment]
You will need this patch until it's merged #503

**Comment by FredBezies** [comment]
Thanks for the patch. Will apply it asap.
